// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeohypupypohmgahlugl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlb2h5cHVweXBvaG1nYWhsdWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjMxNjAsImV4cCI6MjA2MzgzOTE2MH0.8QwZWyebngdQvfg3j6luH-0_KqOOU6b7ZAMkU8vkKZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);